const API_URL="https://libre-y-theta.vercel.app/api.php";
const form=document.getElementById("searchForm"),input=document.getElementById("searchInput"),resultsContainer=document.getElementById("results"),status=document.getElementById("status"),pagination=document.getElementById("pagination"),previousButton=document.getElementById("previousButton"),nextButton=document.getElementById("nextButton"),pageNumber=document.getElementById("pageNumber"),clearButton=document.getElementById("clearButton"),tabs=[...document.querySelectorAll(".tab")];
const home=document.getElementById("home"),resultsPage=document.getElementById("resultsPage"),homeForm=document.getElementById("homeSearchForm"),homeInput=document.getElementById("homeSearchInput"),luckyButton=document.getElementById("luckyButton"),themeButton=document.getElementById("themeButton");
let currentQuery="",currentPage=0,currentType=0,controller=null;
function showResults(){if(home)home.hidden=true;if(resultsPage)resultsPage.hidden=false}
function startSearch(query){query=query.trim();if(!query)return;currentQuery=query;currentPage=0;showResults();if(input)input.value=query;if(clearButton)clearButton.hidden=false;updateURL();search()}
if(homeForm)homeForm.addEventListener("submit",e=>{e.preventDefault();startSearch(homeInput.value)});
if(form)form.addEventListener("submit",e=>{e.preventDefault();startSearch(input.value)});
if(luckyButton)luckyButton.addEventListener("click",()=>{const q=homeInput.value.trim();if(q)startSearch(q)});
if(input)input.addEventListener("input",()=>clearButton.hidden=!input.value);
if(clearButton)clearButton.addEventListener("click",()=>{input.value="";input.focus();clearButton.hidden=true});
if(previousButton)previousButton.addEventListener("click",()=>{if(currentPage>0){currentPage--;updateURL();search()}});
if(nextButton)nextButton.addEventListener("click",()=>{currentPage++;updateURL();search()});
tabs.forEach(tab=>tab.addEventListener("click",()=>{currentType=Number(tab.dataset.type);tabs.forEach(x=>x.classList.toggle("active",x===tab));if(currentQuery){currentPage=0;updateURL();search()}}));
function setTheme(dark){document.documentElement.classList.toggle("dark",dark);if(themeButton){themeButton.textContent=dark?"☀":"☾";themeButton.title=dark?"Switch to light mode":"Switch to dark mode"}localStorage.setItem("libre-ui-theme",dark?"dark":"light")}
const savedTheme=localStorage.getItem("libre-ui-theme");setTheme(savedTheme?savedTheme==="dark":matchMedia("(prefers-color-scheme: dark)").matches);if(themeButton)themeButton.addEventListener("click",()=>setTheme(!document.documentElement.classList.contains("dark")));
async function search(){if(controller)controller.abort();controller=new AbortController();resultsContainer.innerHTML='<div class="loading" aria-label="Searching"><span></span><span></span><span></span></div>';status.textContent=`Searching for “${currentQuery}”…`;pagination.hidden=true;const params=new URLSearchParams({q:currentQuery,p:currentPage,t:currentType});try{const response=await fetch(`${API_URL}?${params}`,{headers:{Accept:"application/json"},signal:controller.signal});if(!response.ok)throw Error(`HTTP ${response.status}`);renderResults(await response.json())}catch(error){if(error.name==="AbortError")return;console.error(error);status.textContent="Search failed";resultsContainer.innerHTML='<div class="error"><strong>Something went wrong.</strong><p>LibreY could not be reached directly.</p><button type="button" onclick="search()">Try again</button></div>'}}
function renderResults(data){resultsContainer.innerHTML="";const results=getResultsArray(data);if(!results.length){status.textContent=data?.error?.message||"No results found.";return}status.textContent=`${results.length} results for “${currentQuery}”`;for(const result of results){if(!result||(!result.title&&!result.url&&!result.description))continue;const title=result.title??result.name??"Untitled",url=result.url??result.link??result.href??"#",description=result.description??result.snippet??result.content??"",element=document.createElement("article");element.className="result";element.innerHTML=`<div class="result-site">${escapeHTML(getHostname(url))}</div><h2 class="result-title"><a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(title)}</a></h2><div class="result-url">${escapeHTML(url)}</div><div class="result-description">${escapeHTML(description)}</div>`;resultsContainer.appendChild(element)}pagination.hidden=false;pageNumber.textContent=`Page ${currentPage+1}`;previousButton.disabled=currentPage===0}
function getResultsArray(data){if(Array.isArray(data))return data;if(Array.isArray(data.results))return data.results;if(Array.isArray(data.data))return data.data;if(Array.isArray(data.items))return data.items;if(data&&typeof data==="object")return Object.keys(data).filter(k=>/^\d+$/.test(k)).sort((a,b)=>Number(a)-Number(b)).map(k=>data[k]);return []}
function getHostname(url){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return ""}}
function updateURL(){const p=new URLSearchParams();if(currentQuery)p.set("q",currentQuery);if(currentPage>0)p.set("p",currentPage);if(currentType>0)p.set("t",currentType);history.replaceState(null,"",p.toString()?`${location.pathname}?${p}`:location.pathname)}
function escapeHTML(value){const el=document.createElement("div");el.textContent=String(value);return el.innerHTML}
function loadFromURL(){const p=new URLSearchParams(location.search),q=p.get("q"),page=parseInt(p.get("p")||"0",10),type=parseInt(p.get("t")||"0",10);currentType=[0,1,2].includes(type)?type:0;tabs.forEach(tab=>tab.classList.toggle("active",Number(tab.dataset.type)===currentType));if(!q)return;currentQuery=q;currentPage=Number.isNaN(page)?0:Math.max(0,page);showResults();input.value=q;clearButton.hidden=false;search()}
loadFromURL();
